#include "RedwingApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<RedwingApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

RedwingApp::RedwingApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  RedwingApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  RedwingApp::associateSyntax(_syntax, _action_factory);
}

RedwingApp::~RedwingApp()
{
}

// External entry point for dynamic application loading
extern "C" void RedwingApp__registerApps() { RedwingApp::registerApps(); }
void
RedwingApp::registerApps()
{
  registerApp(RedwingApp);
}

// External entry point for dynamic object registration
extern "C" void RedwingApp__registerObjects(Factory & factory) { RedwingApp::registerObjects(factory); }
void
RedwingApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void RedwingApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { RedwingApp::associateSyntax(syntax, action_factory); }
void
RedwingApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
